name: Deploy server on Render

on:
  push:
    tags:
      - deploy-server-*
      - release-*
    
jobs:
  Trigger-Render-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: call hook
        run: |
          curl ${{ secrets.RENDER_HOOK_DEPLOY_URL }}