name: Deploy web on Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  PUBLIC_BASE_API_URL: ${{ secrets.PUBLIC_BASE_API_URL }}
  PUBLIC_DEMO_CUSTOMER_PWD: ${{ secrets.PUBLIC_DEMO_CUSTOMER_PWD }}
  PUBLIC_DEMO_CUSTOMER1_PWD: ${{ secrets.PUBLIC_DEMO_CUSTOMER1_PWD }}
on:
  push:
    tags:
      - deploy-web-*
      - release-*
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm i
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}