name: Deploy server on Render

on:
  push:
    tags:
      - deploy-server-*
      - release-*
    
jobs:
  Trigger-Render-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Hey, Deploy server on Render for me please
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"