name: Deploy server on Render

on:
  push:
    tags:
      - deploy-server-*
      - release-*
    
jobs:
  Trigger-Render-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: call hook
        # Only run this step if the branch is main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          curl ${{ secrets.RENDER_HOOK_DEPLOY_URL }}